import React, { useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, Copy, RefreshCcw } from 'lucide-react';
import { ProcessingResult } from '../types';

interface SummaryDisplayProps {
  result: ProcessingResult;
  onReset: () => void;
}

export const SummaryDisplay: React.FC<SummaryDisplayProps> = ({ result, onReset }) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = () => {
    if (!contentRef.current || !window.html2pdf) return;

    const element = contentRef.current;
    const opt = {
      margin:       [0.5, 0.5],
      filename:     `NoteGenie_${new Date().toISOString().slice(0,10)}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2 },
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    // Use html2pdf to generate
    window.html2pdf().set(opt).from(element).save();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result.text);
    // Could add toast here
    alert("Copied to clipboard!");
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
        <div>
          <h2 className="text-xl font-bold text-slate-800 font-burmese">
            {result.type === 'MEETING' ? 'Meeting Minutes' : 'Lecture Notes'}
          </h2>
          <p className="text-sm text-slate-500">
            Generated on {new Date(result.timestamp).toLocaleString()}
          </p>
        </div>
        
        <div className="flex items-center gap-2">
           <button 
            onClick={onReset}
            className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
          >
            <RefreshCcw className="w-4 h-4" />
            <span className="hidden sm:inline">New</span>
          </button>
          <button 
            onClick={handleCopy}
            className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors flex items-center gap-2 text-sm font-medium"
          >
            <Copy className="w-4 h-4" />
            <span className="hidden sm:inline">Copy</span>
          </button>
          <button 
            onClick={handleDownloadPDF}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg shadow-sm transition-colors flex items-center gap-2 text-sm font-medium"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-lg border border-slate-100 overflow-hidden">
        {/* This container is what gets converted to PDF */}
        <div ref={contentRef} className="p-8 md:p-12 min-h-[500px] font-burmese bg-white text-slate-800 leading-relaxed">
           <div className="mb-6 border-b border-slate-100 pb-4">
               <h1 className="text-2xl font-bold text-slate-900 mb-2">
                 {result.type === 'MEETING' ? 'အစည်းအဝေး မှတ်တမ်း' : 'သင်ခန်းစာ အနှစ်ချုပ်'}
               </h1>
               <div className="text-sm text-slate-400">NoteGenie AI Generated Report</div>
           </div>
           
           <div className="prose prose-slate prose-lg max-w-none prose-headings:font-burmese prose-p:font-burmese prose-li:font-burmese">
             <ReactMarkdown>{result.text}</ReactMarkdown>
           </div>
           
           <div className="mt-12 pt-6 border-t border-slate-100 text-center text-xs text-slate-400">
             Generated by NoteGenie AI • {new Date().toLocaleDateString()}
           </div>
        </div>
      </div>
    </div>
  );
};